/*
 * This file is generated by jOOQ.
 */
package com.easyprogramming.app.db.model.enums;


import com.easyprogramming.app.db.model.ScannerApp;

import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum Currency implements EnumType {

    PLN("PLN"),

    USD("USD"),

    EUR("EUR");

    private final String literal;

    private Currency(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return getSchema().getCatalog();
    }

    @Override
    public Schema getSchema() {
        return ScannerApp.SCANNER_APP;
    }

    @Override
    public String getName() {
        return "currency";
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal
     */
    public static Currency lookupLiteral(String literal) {
        return EnumType.lookupLiteral(Currency.class, literal);
    }
}
