/*
 * This file is generated by jOOQ.
 */
package com.easyprogramming.app.db.model.tables;


import com.easyprogramming.app.db.model.Keys;
import com.easyprogramming.app.db.model.ScannerApp;
import com.easyprogramming.app.db.model.enums.Currency;
import com.easyprogramming.app.db.model.tables.records.ProductsRecord;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row5;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Products extends TableImpl<ProductsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>scanner_app.products</code>
     */
    public static final Products PRODUCTS = new Products();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProductsRecord> getRecordType() {
        return ProductsRecord.class;
    }

    /**
     * The column <code>scanner_app.products.id</code>.
     */
    public final TableField<ProductsRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>scanner_app.products.type</code>.
     */
    public final TableField<ProductsRecord, String> TYPE = createField(DSL.name("type"), SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>scanner_app.products.expiration_date</code>.
     */
    public final TableField<ProductsRecord, LocalDateTime> EXPIRATION_DATE = createField(DSL.name("expiration_date"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>scanner_app.products.total_price</code>.
     */
    public final TableField<ProductsRecord, BigDecimal> TOTAL_PRICE = createField(DSL.name("total_price"), SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>scanner_app.products.currency</code>.
     */
    public final TableField<ProductsRecord, Currency> CURRENCY = createField(DSL.name("currency"), SQLDataType.VARCHAR.asEnumDataType(com.easyprogramming.app.db.model.enums.Currency.class), this, "");

    private Products(Name alias, Table<ProductsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Products(Name alias, Table<ProductsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>scanner_app.products</code> table reference
     */
    public Products(String alias) {
        this(DSL.name(alias), PRODUCTS);
    }

    /**
     * Create an aliased <code>scanner_app.products</code> table reference
     */
    public Products(Name alias) {
        this(alias, PRODUCTS);
    }

    /**
     * Create a <code>scanner_app.products</code> table reference
     */
    public Products() {
        this(DSL.name("products"), null);
    }

    public <O extends Record> Products(Table<O> child, ForeignKey<O, ProductsRecord> key) {
        super(child, key, PRODUCTS);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : ScannerApp.SCANNER_APP;
    }

    @Override
    public UniqueKey<ProductsRecord> getPrimaryKey() {
        return Keys.PRODUCTS_PKEY;
    }

    @Override
    public Products as(String alias) {
        return new Products(DSL.name(alias), this);
    }

    @Override
    public Products as(Name alias) {
        return new Products(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Products rename(String name) {
        return new Products(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Products rename(Name name) {
        return new Products(name, null);
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row5<UUID, String, LocalDateTime, BigDecimal, Currency> fieldsRow() {
        return (Row5) super.fieldsRow();
    }
}
