/*
 * This file is generated by jOOQ.
 */
package com.easyprogramming.app.db.model;


import com.easyprogramming.app.db.model.tables.Orders;
import com.easyprogramming.app.db.model.tables.OrdersDescription;
import com.easyprogramming.app.db.model.tables.Products;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ScannerApp extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>scanner_app</code>
     */
    public static final ScannerApp SCANNER_APP = new ScannerApp();

    /**
     * The table <code>scanner_app.orders</code>.
     */
    public final Orders ORDERS = Orders.ORDERS;

    /**
     * The table <code>scanner_app.orders_description</code>.
     */
    public final OrdersDescription ORDERS_DESCRIPTION = OrdersDescription.ORDERS_DESCRIPTION;

    /**
     * The table <code>scanner_app.products</code>.
     */
    public final Products PRODUCTS = Products.PRODUCTS;

    /**
     * No further instances allowed
     */
    private ScannerApp() {
        super("scanner_app", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Orders.ORDERS,
            OrdersDescription.ORDERS_DESCRIPTION,
            Products.PRODUCTS
        );
    }
}
