/*
 * This file is generated by jOOQ.
 */
package com.easyprogramming.app.db.model;


import com.easyprogramming.app.db.model.tables.Orders;
import com.easyprogramming.app.db.model.tables.OrdersDescription;
import com.easyprogramming.app.db.model.tables.Products;


/**
 * Convenience access to all tables in scanner_app.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>scanner_app.orders</code>.
     */
    public static final Orders ORDERS = Orders.ORDERS;

    /**
     * The table <code>scanner_app.orders_description</code>.
     */
    public static final OrdersDescription ORDERS_DESCRIPTION = OrdersDescription.ORDERS_DESCRIPTION;

    /**
     * The table <code>scanner_app.products</code>.
     */
    public static final Products PRODUCTS = Products.PRODUCTS;
}
